//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Polynomial.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Antlr4.Polynomial {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PolynomialParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IPolynomialListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>monomialSum</c>
	/// labeled alternative in <see cref="PolynomialParser.polynomial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMonomialSum([NotNull] PolynomialParser.MonomialSumContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>monomialSum</c>
	/// labeled alternative in <see cref="PolynomialParser.polynomial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMonomialSum([NotNull] PolynomialParser.MonomialSumContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>realMonomial</c>
	/// labeled alternative in <see cref="PolynomialParser.monomial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRealMonomial([NotNull] PolynomialParser.RealMonomialContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>realMonomial</c>
	/// labeled alternative in <see cref="PolynomialParser.monomial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRealMonomial([NotNull] PolynomialParser.RealMonomialContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>const</c>
	/// labeled alternative in <see cref="PolynomialParser.monomial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst([NotNull] PolynomialParser.ConstContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>const</c>
	/// labeled alternative in <see cref="PolynomialParser.monomial"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst([NotNull] PolynomialParser.ConstContext context);
}
} // namespace Antlr4.Polynomial
