//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Polynomial.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class PolynomialParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, NUM=2, VAR=3, SIGN=4, POWER=5, WS=6;
	public const int
		RULE_polynomial = 0, RULE_monomial = 1, RULE_monom = 2;
	public static readonly string[] ruleNames = {
		"polynomial", "monomial", "monom"
	};

	private static readonly string[] _LiteralNames = {
		null, "'*'", null, null, null, "'^'", "' '"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "NUM", "VAR", "SIGN", "POWER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Polynomial.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static PolynomialParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PolynomialParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PolynomialParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class PolynomialContext : ParserRuleContext {
		public PolynomialContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_polynomial; } }
	 
		public PolynomialContext() { }
		public virtual void CopyFrom(PolynomialContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MonomialSumContext : PolynomialContext {
		public MonomialContext[] monomial() {
			return GetRuleContexts<MonomialContext>();
		}
		public MonomialContext monomial(int i) {
			return GetRuleContext<MonomialContext>(i);
		}
		public ITerminalNode[] SIGN() { return GetTokens(PolynomialParser.SIGN); }
		public ITerminalNode SIGN(int i) {
			return GetToken(PolynomialParser.SIGN, i);
		}
		public MonomialSumContext(PolynomialContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.EnterMonomialSum(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.ExitMonomialSum(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPolynomialVisitor<TResult> typedVisitor = visitor as IPolynomialVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMonomialSum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PolynomialContext polynomial() {
		PolynomialContext _localctx = new PolynomialContext(Context, State);
		EnterRule(_localctx, 0, RULE_polynomial);
		int _la;
		try {
			_localctx = new MonomialSumContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 7;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SIGN) {
				{
				State = 6; Match(SIGN);
				}
			}

			State = 9; monomial();
			}
			State = 15;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SIGN) {
				{
				{
				State = 11; Match(SIGN);
				State = 12; monomial();
				}
				}
				State = 17;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MonomialContext : ParserRuleContext {
		public MonomialContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_monomial; } }
	 
		public MonomialContext() { }
		public virtual void CopyFrom(MonomialContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class RealMonomialContext : MonomialContext {
		public ITerminalNode[] NUM() { return GetTokens(PolynomialParser.NUM); }
		public ITerminalNode NUM(int i) {
			return GetToken(PolynomialParser.NUM, i);
		}
		public ITerminalNode[] VAR() { return GetTokens(PolynomialParser.VAR); }
		public ITerminalNode VAR(int i) {
			return GetToken(PolynomialParser.VAR, i);
		}
		public ITerminalNode[] POWER() { return GetTokens(PolynomialParser.POWER); }
		public ITerminalNode POWER(int i) {
			return GetToken(PolynomialParser.POWER, i);
		}
		public RealMonomialContext(MonomialContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.EnterRealMonomial(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.ExitRealMonomial(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPolynomialVisitor<TResult> typedVisitor = visitor as IPolynomialVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRealMonomial(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ConstContext : MonomialContext {
		public ITerminalNode NUM() { return GetToken(PolynomialParser.NUM, 0); }
		public ConstContext(MonomialContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.EnterConst(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.ExitConst(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPolynomialVisitor<TResult> typedVisitor = visitor as IPolynomialVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConst(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MonomialContext monomial() {
		MonomialContext _localctx = new MonomialContext(Context, State);
		EnterRule(_localctx, 2, RULE_monomial);
		int _la;
		try {
			State = 34;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				_localctx = new RealMonomialContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 19;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NUM) {
					{
					State = 18; Match(NUM);
					}
				}

				State = 22;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__0) {
					{
					State = 21; Match(T__0);
					}
				}

				State = 29;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 24; Match(VAR);
					State = 27;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==POWER) {
						{
						State = 25; Match(POWER);
						State = 26; Match(NUM);
						}
					}

					}
					}
					State = 31;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==VAR );
				}
				break;
			case 2:
				_localctx = new ConstContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 33; Match(NUM);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MonomContext : ParserRuleContext {
		public ITerminalNode[] VAR() { return GetTokens(PolynomialParser.VAR); }
		public ITerminalNode VAR(int i) {
			return GetToken(PolynomialParser.VAR, i);
		}
		public ITerminalNode[] POWER() { return GetTokens(PolynomialParser.POWER); }
		public ITerminalNode POWER(int i) {
			return GetToken(PolynomialParser.POWER, i);
		}
		public ITerminalNode[] NUM() { return GetTokens(PolynomialParser.NUM); }
		public ITerminalNode NUM(int i) {
			return GetToken(PolynomialParser.NUM, i);
		}
		public MonomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_monom; } }
		public override void EnterRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.EnterMonom(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IPolynomialListener typedListener = listener as IPolynomialListener;
			if (typedListener != null) typedListener.ExitMonom(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPolynomialVisitor<TResult> typedVisitor = visitor as IPolynomialVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMonom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MonomContext monom() {
		MonomContext _localctx = new MonomContext(Context, State);
		EnterRule(_localctx, 4, RULE_monom);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 36; Match(VAR);
				State = 39;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==POWER) {
					{
					State = 37; Match(POWER);
					State = 38; Match(NUM);
					}
				}

				}
				}
				State = 43;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==VAR );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\b', '\x30', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x3', '\x2', '\x5', '\x2', '\n', 
		'\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', 
		'\x2', '\x10', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x13', '\v', '\x2', 
		'\x3', '\x3', '\x5', '\x3', '\x16', '\n', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '\x19', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', '\x1E', '\n', '\x3', '\x6', '\x3', ' ', '\n', '\x3', '\r', 
		'\x3', '\xE', '\x3', '!', '\x3', '\x3', '\x5', '\x3', '%', '\n', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '*', '\n', '\x4', 
		'\x6', '\x4', ',', '\n', '\x4', '\r', '\x4', '\xE', '\x4', '-', '\x3', 
		'\x4', '\x2', '\x2', '\x5', '\x2', '\x4', '\x6', '\x2', '\x2', '\x2', 
		'\x35', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x4', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '+', '\x3', '\x2', '\x2', '\x2', '\b', '\n', '\a', 
		'\x6', '\x2', '\x2', '\t', '\b', '\x3', '\x2', '\x2', '\x2', '\t', '\n', 
		'\x3', '\x2', '\x2', '\x2', '\n', '\v', '\x3', '\x2', '\x2', '\x2', '\v', 
		'\f', '\x5', '\x4', '\x3', '\x2', '\f', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\r', '\xE', '\a', '\x6', '\x2', '\x2', '\xE', '\x10', '\x5', '\x4', '\x3', 
		'\x2', '\xF', '\r', '\x3', '\x2', '\x2', '\x2', '\x10', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x11', '\xF', '\x3', '\x2', '\x2', '\x2', '\x11', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x12', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '\x11', '\x3', '\x2', '\x2', '\x2', '\x14', '\x16', '\a', 
		'\x4', '\x2', '\x2', '\x15', '\x14', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x16', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x19', '\a', '\x3', '\x2', '\x2', '\x18', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x19', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x1D', '\a', '\x5', '\x2', 
		'\x2', '\x1B', '\x1C', '\a', '\a', '\x2', '\x2', '\x1C', '\x1E', '\a', 
		'\x4', '\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x1E', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x1A', '\x3', '\x2', '\x2', '\x2', ' ', '!', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x1F', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\"', '%', '\x3', '\x2', '\x2', '\x2', '#', '%', 
		'\a', '\x4', '\x2', '\x2', '$', '\x15', '\x3', '\x2', '\x2', '\x2', '$', 
		'#', '\x3', '\x2', '\x2', '\x2', '%', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'&', ')', '\a', '\x5', '\x2', '\x2', '\'', '(', '\a', '\a', '\x2', '\x2', 
		'(', '*', '\a', '\x4', '\x2', '\x2', ')', '\'', '\x3', '\x2', '\x2', '\x2', 
		')', '*', '\x3', '\x2', '\x2', '\x2', '*', ',', '\x3', '\x2', '\x2', '\x2', 
		'+', '&', '\x3', '\x2', '\x2', '\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', 
		'-', '+', '\x3', '\x2', '\x2', '\x2', '-', '.', '\x3', '\x2', '\x2', '\x2', 
		'.', '\a', '\x3', '\x2', '\x2', '\x2', '\v', '\t', '\x11', '\x15', '\x18', 
		'\x1D', '!', '$', ')', '-',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
